var searchData=
[
  ['acceleration',['acceleration',['../namespaceunits_1_1acceleration.html',1,'units']]],
  ['angle',['angle',['../namespaceunits_1_1angle.html',1,'units']]],
  ['angular_5fvelocity',['angular_velocity',['../namespaceunits_1_1angular__velocity.html',1,'units']]],
  ['area',['area',['../namespaceunits_1_1area.html',1,'units']]],
  ['capacitance',['capacitance',['../namespaceunits_1_1capacitance.html',1,'units']]],
  ['category',['category',['../namespaceunits_1_1category.html',1,'units']]],
  ['charge',['charge',['../namespaceunits_1_1charge.html',1,'units']]],
  ['concentration',['concentration',['../namespaceunits_1_1concentration.html',1,'units']]],
  ['conductance',['conductance',['../namespaceunits_1_1conductance.html',1,'units']]],
  ['constants',['constants',['../namespaceunits_1_1constants.html',1,'units']]],
  ['current',['current',['../namespaceunits_1_1current.html',1,'units']]],
  ['density',['density',['../namespaceunits_1_1density.html',1,'units']]],
  ['dimensionless',['dimensionless',['../namespaceunits_1_1dimensionless.html',1,'units']]],
  ['energy',['energy',['../namespaceunits_1_1energy.html',1,'units']]],
  ['force',['force',['../namespaceunits_1_1force.html',1,'units']]],
  ['frequency',['frequency',['../namespaceunits_1_1frequency.html',1,'units']]],
  ['illuminance',['illuminance',['../namespaceunits_1_1illuminance.html',1,'units']]],
  ['impedance',['impedance',['../namespaceunits_1_1impedance.html',1,'units']]],
  ['units_20_3ca_20href_3d_22https_3a_2f_2ftravis_2dci_2eorg_2fnholthaus_2funits_22_20target_3d_22_5fblank_22_3e_3cimg_20src_3d_22https_3a_2f_2ftravis_2dci_2eorg_2fnholthaus_2funits_2esvg_3fbranch_3dmaster_22_2f_3e_3c_2fa_3e_20_3ca_20href_3d_22https_3a_2f_2fci_2eappveyor_2ecom_2fproject_2fnholthaus_2funits_22_20target_3d_22_5fblank_22_3e_3cimg_20src_3d_22https_3a_2f_2fci_2eappveyor_2ecom_2fapi_2fprojects_2fstatus_2fgithub_2fnholthaus_2funits_3fsvg_3dtrue_22_2f_3e_3c_2fa_3e',['units &lt;a href=&quot;https://travis-ci.org/nholthaus/units&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;https://travis-ci.org/nholthaus/units.svg?branch=master&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://ci.appveyor.com/project/nholthaus/units&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;https://ci.appveyor.com/api/projects/status/github/nholthaus/units?svg=true&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['inductance',['inductance',['../namespaceunits_1_1inductance.html',1,'units']]],
  ['length',['length',['../namespaceunits_1_1length.html',1,'units']]],
  ['luminous_5fflux',['luminous_flux',['../namespaceunits_1_1luminous__flux.html',1,'units']]],
  ['luminous_5fintensity',['luminous_intensity',['../namespaceunits_1_1luminous__intensity.html',1,'units']]],
  ['magnetic_5ffield_5fstrength',['magnetic_field_strength',['../namespaceunits_1_1magnetic__field__strength.html',1,'units']]],
  ['magnetic_5fflux',['magnetic_flux',['../namespaceunits_1_1magnetic__flux.html',1,'units']]],
  ['mass',['mass',['../namespaceunits_1_1mass.html',1,'units']]],
  ['math',['math',['../namespaceunits_1_1math.html',1,'units']]],
  ['power',['power',['../namespaceunits_1_1power.html',1,'units']]],
  ['pressure',['pressure',['../namespaceunits_1_1pressure.html',1,'units']]],
  ['radiation',['radiation',['../namespaceunits_1_1radiation.html',1,'units']]],
  ['solid_5fangle',['solid_angle',['../namespaceunits_1_1solid__angle.html',1,'units']]],
  ['substance',['substance',['../namespaceunits_1_1substance.html',1,'units']]],
  ['temperature',['temperature',['../namespaceunits_1_1temperature.html',1,'units']]],
  ['time',['time',['../namespaceunits_1_1time.html',1,'units']]],
  ['torque',['torque',['../namespaceunits_1_1torque.html',1,'units']]],
  ['traits',['traits',['../namespaceunits_1_1traits.html',1,'units']]],
  ['underlying_5ftype',['underlying_type',['../structunits_1_1traits_1_1unit__t__traits.html#a67f44ead54d0f792f094a1e6eddbe51c',1,'units::traits::unit_t_traits::underlying_type()'],['../classunits_1_1unit__t.html#af3f88305faf59e0c71e8e616a2877ceb',1,'units::unit_t::underlying_type()']]],
  ['unit',['unit',['../structunits_1_1unit.html',1,'units']]],
  ['unit_5ft',['unit_t',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft',['unit_t',['../classunits_1_1unit__t.html#aebd4c88e33ce27f1d406794485e03358',1,'units::unit_t::unit_t()=default'],['../classunits_1_1unit__t.html#aa4a3c6a0723a72c27255362ec27a4a25',1,'units::unit_t::unit_t(T value, const Args &amp;...args)'],['../classunits_1_1unit__t.html#a240aa805d5149ebcf2c90f72c0d6561d',1,'units::unit_t::unit_t(Ty value)'],['../classunits_1_1unit__t.html#aa50a999bfebc187549f281de23f5afe7',1,'units::unit_t::unit_t(const unit_t&lt; UnitsRhs, Ty, NlsRhs &gt; &amp;rhs)']]],
  ['unit_5ft_5ftraits',['unit_t_traits',['../structunits_1_1traits_1_1unit__t__traits.html',1,'units::traits']]],
  ['unit_5ftraits',['unit_traits',['../structunits_1_1traits_1_1unit__traits.html',1,'units::traits']]],
  ['unit_5ftype',['unit_type',['../structunits_1_1traits_1_1unit__t__traits.html#a6de485677a031bd6051b8d4cbcfd38fb',1,'units::traits::unit_t_traits::unit_type()'],['../classunits_1_1unit__t.html#a97925b5862ffd961071a8060d0f036b3',1,'units::unit_t::unit_type()'],['../structunits_1_1traits_1_1unit__value__t__traits.html#a55b452f45b9191f73feda1a511376a6f',1,'units::traits::unit_value_t_traits::unit_type()']]],
  ['unit_5fvalue_5fadd',['unit_value_add',['../structunits_1_1unit__value__add.html',1,'units']]],
  ['unit_5fvalue_5fdivide',['unit_value_divide',['../structunits_1_1unit__value__divide.html',1,'units']]],
  ['unit_5fvalue_5fmultiply',['unit_value_multiply',['../structunits_1_1unit__value__multiply.html',1,'units']]],
  ['unit_5fvalue_5fpower',['unit_value_power',['../structunits_1_1unit__value__power.html',1,'units']]],
  ['unit_5fvalue_5fsqrt',['unit_value_sqrt',['../structunits_1_1unit__value__sqrt.html',1,'units']]],
  ['unit_5fvalue_5fsubtract',['unit_value_subtract',['../structunits_1_1unit__value__subtract.html',1,'units']]],
  ['unit_5fvalue_5ft',['unit_value_t',['../structunits_1_1unit__value__t.html',1,'units']]],
  ['unit_5fvalue_5ft_5ftraits',['unit_value_t_traits',['../structunits_1_1traits_1_1unit__value__t__traits.html',1,'units::traits']]],
  ['unit_20containers',['Unit Containers',['../group___unit_containers.html',1,'']]],
  ['unit_20manipulators',['Unit Manipulators',['../group___unit_manipulators.html',1,'']]],
  ['unit_20math',['Unit Math',['../group___unit_math.html',1,'']]],
  ['units',['units',['../namespaceunits.html',1,'']]],
  ['units_2eh',['units.h',['../units_8h.html',1,'']]],
  ['unit_20types',['Unit Types',['../group___unit_types.html',1,'']]],
  ['velocity',['velocity',['../namespaceunits_1_1velocity.html',1,'units']]],
  ['voltage',['voltage',['../namespaceunits_1_1voltage.html',1,'units']]],
  ['volume',['volume',['../namespaceunits_1_1volume.html',1,'units']]]
];
