.TH "Conversion" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Conversion \- Explicit Conversion
.PP
Functions used to convert values of one logical type to another\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class UnitFrom , class UnitTo , typename T  = double> static T \fBunits::convert\fP (const T &value)"
.br
.RI "\fIconverts a \fIvalue\fP from one type to another\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions used to convert values of one logical type to another\&. 


.SH "Function Documentation"
.PP 
.SS "template<class UnitFrom , class UnitTo , typename T  = double> static T units::convert (const T & value)\fC [inline]\fP, \fC [static]\fP"

.PP
converts a \fIvalue\fP from one type to another\&. Converts a \fIvalue\fP of a built-in arithmetic type to another unit\&. This does not change the type of \fIvalue\fP, only what it contains\&. E\&.g\&.
.PP
.nf
double result = convert<length::meters, length::feet>(1\&.0);  // result == 3\&.28084 

.fi
.PP
 
.PP
\fBSee also:\fP
.RS 4
\fBunit_t\fP for implicit conversion of \fBunit\fP containers\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIUnitFrom\fP unit tag to convert \fIvalue\fP from\&. Must be a \fCunit\fP type (i\&.e\&. is_unit<UnitFrom>::value == true), and must be convertible to \fCUnitTo\fP (i\&.e\&. is_converitble_unit<UnitFrom, UnitTo>::value == true)\&. 
.br
\fIUnitTo\fP unit tag to convert \fIvalue\fP to\&. Must be a \fCunit\fP type (i\&.e\&. is_unit<UnitTo>::value == true), and must be convertible from \fCUnitFrom\fP (i\&.e\&. is_converitble_unit<UnitFrom, UnitTo>::value == true)\&. 
.br
\fIT\fP type of \fIvalue\fP\&. It is infered from \fIvalue\fP, and is expected to be a built-in arethmetic type\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP Arithmetic value to convert from \fCUnitFrom\fP to \fCUnitTo\fP\&. The value should represent a quantity in units of \fCUnitFrom\fP\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
value, converted from units of \fCUnitFrom\fP to \fCUnitTo\fP\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
