.TH "units::traits::is_unit_t< T >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::traits::is_unit_t< T > \- Traits which tests if a class is a \fCunit\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.PP
Inherits type< detail::_unit_t, T >\&.
.SH "Detailed Description"
.PP 

.SS "template<class T>struct units::traits::is_unit_t< T >"
Traits which tests if a class is a \fCunit\fP 

Inherits from \fCstd::true_type\fP or \fCstd::false_type\fP\&. Use \fC\fBis_unit\fP<T>::value\fP to test whether \fCclass T\fP implements a \fCunit\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
