.TH "units::decibel_scale< T >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::decibel_scale< T > \- \fBunit_t\fP scale for representing decibel values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdecibel_scale\fP (T value)"
.br
.ti -1c
.RI "T \fBoperator()\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBm_value\fP"
.br
.RI "\fIlinearized value \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct units::decibel_scale< T >"
\fBunit_t\fP scale for representing decibel values\&. 

internally stores linearized values\&. \fCoperator()\fP returns the value in dB\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP underlying storage type 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBunit_t\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
