.TH "units::velocity" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::velocity \- namespace for unit types and containers representing velocity values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBmeters_per_second\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::velocity_unit\fP >"
.br
.ti -1c
.RI "using \fBfeet_per_second\fP = \fBcompound_unit\fP< \fBlength::feet\fP, \fBinverse\fP< \fBtime::seconds\fP >>"
.br
.ti -1c
.RI "using \fBmiles_per_hour\fP = \fBcompound_unit\fP< \fBlength::miles\fP, \fBinverse\fP< \fBtime::hour\fP >>"
.br
.ti -1c
.RI "using \fBkilometers_per_hour\fP = \fBcompound_unit\fP< length::kilometers, \fBinverse\fP< \fBtime::hour\fP >>"
.br
.ti -1c
.RI "using \fBknots\fP = \fBcompound_unit\fP< \fBlength::nauticalMiles\fP, \fBinverse\fP< \fBtime::hour\fP >>"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBknot\fP = knots"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBmps\fP = \fBmeters_per_second\fP"
.br
.ti -1c
.RI "using \fBmph\fP = miles_per_hour"
.br
.ti -1c
.RI "using \fBfps\fP = feet_per_second"
.br
.ti -1c
.RI "using \fBkmph\fP = kilometers_per_hour"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBmeters_per_second_t\fP = \fBunit_t\fP< \fBmeters_per_second\fP >"
.br
.ti -1c
.RI "using \fBfeet_per_second_t\fP = \fBunit_t\fP< feet_per_second >"
.br
.ti -1c
.RI "using \fBmiles_per_hour_t\fP = \fBunit_t\fP< miles_per_hour >"
.br
.ti -1c
.RI "using \fBkilometers_per_hour_t\fP = \fBunit_t\fP< kilometers_per_hour >"
.br
.ti -1c
.RI "using \fBknot_t\fP = \fBunit_t\fP< knot >"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing velocity values 

The SI unit for velocity is \fCmeters_per_second\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCvelocity_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
