.TH "units::solid_angle" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::solid_angle \- namespace for unit types and containers representing \fBsolid_angle\fP values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBsteradians\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::solid_angle_unit\fP >"
.br
.ti -1c
.RI "using \fBdegrees_squared\fP = \fBsquared\fP< \fBangle::degrees\fP >"
.br
.ti -1c
.RI "using \fBspats\fP = \fBunit\fP< std::ratio< 4 >, \fBsteradians\fP, std::ratio< 1 >>"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBsteradian\fP = \fBsteradians\fP"
.br
.ti -1c
.RI "using \fBdegree_squared\fP = degrees_squared"
.br
.ti -1c
.RI "using \fBspat\fP = \fBspats\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBsr\fP = \fBsteradians\fP"
.br
.ti -1c
.RI "using \fBsq_deg\fP = degrees_squared"
.br
.ti -1c
.RI "using \fBsp\fP = \fBspat\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBsteradian_t\fP = \fBunit_t\fP< \fBsteradian\fP >"
.br
.ti -1c
.RI "using \fBdegree_squared_t\fP = \fBunit_t\fP< degree_squared >"
.br
.ti -1c
.RI "using \fBspat_t\fP = \fBunit_t\fP< \fBspat\fP >"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing \fBsolid_angle\fP values 

The SI unit for \fBsolid_angle\fP is \fCsteradians\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCsolid_angle_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
