.TH "units::conductance" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::conductance \- namespace for unit types and containers representing conductance values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBsiemens\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::conductance_unit\fP >"
.br
.ti -1c
.RI "using \fBpicosiemens\fP = \fBpico\fP< \fBsiemens\fP >"
.br
.ti -1c
.RI "using \fBnanosiemens\fP = \fBnano\fP< \fBsiemens\fP >"
.br
.ti -1c
.RI "using \fBmicrosiemens\fP = \fBmicro\fP< \fBsiemens\fP >"
.br
.ti -1c
.RI "using \fBmillisiemens\fP = \fBmilli\fP< \fBsiemens\fP >"
.br
.ti -1c
.RI "using \fBkilosiemens\fP = \fBkilo\fP< \fBsiemens\fP >"
.br
.ti -1c
.RI "using \fBmegasiemens\fP = \fBmega\fP< \fBsiemens\fP >"
.br
.ti -1c
.RI "using \fBgigasiemens\fP = \fBgiga\fP< \fBsiemens\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBsiemen\fP = \fBsiemens\fP"
.br
.ti -1c
.RI "using \fBpicosiemen\fP = picosiemens"
.br
.ti -1c
.RI "using \fBnanosiemen\fP = nanosiemens"
.br
.ti -1c
.RI "using \fBmicrosiemen\fP = microsiemens"
.br
.ti -1c
.RI "using \fBmillisiemen\fP = millisiemens"
.br
.ti -1c
.RI "using \fBkilosiemen\fP = kilosiemens"
.br
.ti -1c
.RI "using \fBmegasiemen\fP = megasiemens"
.br
.ti -1c
.RI "using \fBgigasiemen\fP = gigasiemens"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBsiemen_t\fP = \fBunit_t\fP< \fBsiemen\fP >"
.br
.ti -1c
.RI "using \fBpicosiemen_t\fP = \fBunit_t\fP< picosiemen >"
.br
.ti -1c
.RI "using \fBnanosiemen_t\fP = \fBunit_t\fP< nanosiemen >"
.br
.ti -1c
.RI "using \fBmicrosiemen_t\fP = \fBunit_t\fP< microsiemen >"
.br
.ti -1c
.RI "using \fBmillisiemen_t\fP = \fBunit_t\fP< millisiemen >"
.br
.ti -1c
.RI "using \fBkilosiemen_t\fP = \fBunit_t\fP< kilosiemen >"
.br
.ti -1c
.RI "using \fBmegasiemen_t\fP = \fBunit_t\fP< megasiemen >"
.br
.ti -1c
.RI "using \fBgigasiemen_t\fP = \fBunit_t\fP< gigasiemen >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBS\fP = \fBsiemens\fP"
.br
.ti -1c
.RI "using \fBpS\fP = picosiemens"
.br
.ti -1c
.RI "using \fBnS\fP = nanosiemens"
.br
.ti -1c
.RI "using \fBuS\fP = microsiemens"
.br
.ti -1c
.RI "using \fBmS\fP = millisiemens"
.br
.ti -1c
.RI "using \fBkS\fP = kilosiemens"
.br
.ti -1c
.RI "using \fBMS\fP = megasiemens"
.br
.ti -1c
.RI "using \fBGS\fP = gigasiemens"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing conductance values 

The SI unit for conductance is \fCsiemens\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCconductance_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
