.TH "units::traits::unit_value_t_traits< T >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::traits::unit_value_t_traits< T > \- Trait for accessing the publically defined types of \fCunits::unit_value_t_traits\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T::unit_type \fBunit_type\fP"
.br
.RI "\fIDimension represented by the \fC\fBunit_value_t\fP\fP\&. \fP"
.ti -1c
.RI "typedef T::ratio \fBratio\fP"
.br
.RI "\fIQuantity represented by the \fC\fBunit_value_t\fP\fP, expressed as arational number\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct units::traits::unit_value_t_traits< T >"
Trait for accessing the publically defined types of \fCunits::unit_value_t_traits\fP 

The units library determines certain properties of the \fC\fBunit_value_t\fP\fP types passed to them and what they represent by using the members of the corresponding \fC\fBunit_value_t_traits\fP\fP instantiation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
