.TH "units::acceleration" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::acceleration \- namespace for unit types and containers representing acceleration values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBmeters_per_second_squared\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::acceleration_unit\fP >"
.br
.ti -1c
.RI "using \fBfeet_per_second_squared\fP = \fBcompound_unit\fP< \fBlength::feet\fP, \fBinverse\fP< \fBsquared\fP< \fBtime::seconds\fP >>>"
.br
.ti -1c
.RI "using \fBstandard_gravity\fP = \fBunit\fP< std::ratio< 980665, 100000 >, \fBmeters_per_second_squared\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBmeters_per_second_squared_t\fP = \fBunit_t\fP< \fBmeters_per_second_squared\fP >"
.br
.ti -1c
.RI "using \fBfeet_per_second_squared_t\fP = \fBunit_t\fP< feet_per_second_squared >"
.br
.ti -1c
.RI "using \fBstandard_gravity_t\fP = \fBunit_t\fP< \fBstandard_gravity\fP >"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing acceleration values 

The SI unit for acceleration is \fCmeters_per_second_squared\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCacceleration_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
