.TH "units::torque" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::torque \- namespace for unit types and containers representing torque values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBnewton_meters\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::torque_unit\fP >"
.br
.ti -1c
.RI "using \fBfoot_pounds\fP = \fBcompound_unit\fP< \fBlength::foot\fP, force::pounds >"
.br
.ti -1c
.RI "using \fBfoot_poundals\fP = \fBcompound_unit\fP< \fBlength::foot\fP, force::poundal >"
.br
.ti -1c
.RI "using \fBinch_pounds\fP = \fBcompound_unit\fP< \fBlength::inch\fP, force::pounds >"
.br
.ti -1c
.RI "using \fBmeter_kilograms\fP = \fBcompound_unit\fP< \fBlength::meter\fP, force::kiloponds >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBnewton_meter\fP = \fBnewton_meters\fP"
.br
.ti -1c
.RI "using \fBfoot_pound\fP = foot_pounds"
.br
.ti -1c
.RI "using \fBfoot_poundal\fP = foot_poundals"
.br
.ti -1c
.RI "using \fBinch_pound\fP = inch_pounds"
.br
.ti -1c
.RI "using \fBmeter_kilogram\fP = meter_kilograms"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBnewton_meter_t\fP = \fBunit_t\fP< \fBnewton_meter\fP >"
.br
.ti -1c
.RI "using \fBfoot_pound_t\fP = \fBunit_t\fP< foot_pound >"
.br
.ti -1c
.RI "using \fBfoot_poundal_t\fP = \fBunit_t\fP< foot_poundal >"
.br
.ti -1c
.RI "using \fBinch_pound_t\fP = \fBunit_t\fP< inch_pound >"
.br
.ti -1c
.RI "using \fBmeter_kilogram_t\fP = \fBunit_t\fP< meter_kilogram >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBNm\fP = \fBnewton_meters\fP"
.br
.ti -1c
.RI "using \fBftlbf\fP = foot_pounds"
.br
.ti -1c
.RI "using \fBftpdl\fP = foot_poundals"
.br
.ti -1c
.RI "using \fBinlbf\fP = inch_pounds"
.br
.ti -1c
.RI "using \fBmkgf\fP = meter_kilograms"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing torque values 

The SI unit for torque is \fCnewton_meters\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCtorque_units\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
