.TH "units::unit_value_t< Units, Num, Denom >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::unit_value_t< Units, Num, Denom > \- Stores a rational unit value as a compile-time constant\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.PP
Inherits _unit_value_t< Units >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Units \fBunit_type\fP"
.br
.ti -1c
.RI "typedef std::ratio< Num, Denom > \fBratio\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBunit_t\fP< Units > \fBvalue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Units, std::uintmax_t Num, std::uintmax_t Denom = 1>struct units::unit_value_t< Units, Num, Denom >"
Stores a rational unit value as a compile-time constant\&. 

\fBunit_value_t\fP is useful for performing compile-time arithmetic on known unit quantities\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIUnits\fP units represented by the \fC\fBunit_value_t\fP\fP 
.br
\fINum\fP numerator of the represented value\&. 
.br
\fIDenom\fP denominator of the represented value\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
unit_value_t_traits to access information about the properties of the class, such as it's \fBunit\fP type and rational value\&. 
.RE
.PP
\fBNote:\fP
.RS 4
This is intentionally identical in concept to a \fCstd::ratio\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
