.TH "units::traits::is_unit_value_t< T, Units >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::traits::is_unit_value_t< T, Units > \- Trait which tests whether a type is a \fBunit_value_t\fP representing the given unit type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.PP
Inherits integral_constant< bool, std::is_base_of< detail::_unit_value_t< Units >, T >::value >\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Units = typename traits::unit_value_t_traits<T>::unit_type>struct units::traits::is_unit_value_t< T, Units >"
Trait which tests whether a type is a \fBunit_value_t\fP representing the given unit type\&. 

e\&.g\&. \fC\fBis_unit_value_t\fP<meters, myType>::value\fP would test that \fCmyType\fP is a \fC\fBunit_value_t\fP<meters>\fP\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIUnits\fP units that the \fC\fBunit_value_t\fP\fP is supposed to have\&. 
.br
\fIT\fP type to test\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
