.TH "units::base_unit< Meter, Kilogram, Second, Radian, Ampere, Kelvin, Mole, Candela >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::base_unit< Meter, Kilogram, Second, Radian, Ampere, Kelvin, Mole, Candela > \- Class representing SI base unit types\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.PP
Inherits _base_unit_t\&.
.SH "Detailed Description"
.PP 

.SS "template<class Meter = std::ratio<0>, class Kilogram = std::ratio<0>, class Second = std::ratio<0>, class Radian = std::ratio<0>, class Ampere = std::ratio<0>, class Kelvin = std::ratio<0>, class Mole = std::ratio<0>, class Candela = std::ratio < 0 >>struct units::base_unit< Meter, Kilogram, Second, Radian, Ampere, Kelvin, Mole, Candela >"
Class representing SI base unit types\&. 

Base units are represented by a combination of \fCstd::ratio\fP template parameters, each describing the exponent of the type of unit they represent\&. Example: meters per second would be described by a +1 exponent for meters, and a -1 exponent for seconds, thus: \fC\fBbase_unit\fP<std::ratio<1>, std::ratio<0>, std::ratio<-1>>\fP 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIMeter\fP \fCstd::ratio\fP representing the exponent value for meters\&. 
.br
\fIKilogram\fP \fCstd::ratio\fP representing the exponent value for kilograms\&. 
.br
\fISecond\fP \fCstd::ratio\fP representing the exponent value for seconds\&. 
.br
\fIRadian\fP \fCstd::ratio\fP representing the exponent value for radians\&. Although radians are not SI base units, they are included because radians are described by the SI as m * m^-1, which would make them indistinguishable from scalars\&. 
.br
\fIAmpere\fP \fCstd::ratio\fP representing the exponent value for amperes\&. 
.br
\fIKelvin\fP \fCstd::ratio\fP representing the exponent value for Kelvin\&. 
.br
\fIMole\fP \fCstd::ratio\fP representing the exponent value for moles\&. 
.br
\fICandela\fP \fCstd::ratio\fP representing the exponent value for candelas\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBcategory\fP for type aliases for SI \fBbase_unit\fP types\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
