.TH "units::voltage" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::voltage \- namespace for unit types and containers representing voltage values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBvolts\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::voltage_unit\fP >"
.br
.ti -1c
.RI "using \fBpicovolts\fP = \fBpico\fP< \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBnanovolts\fP = \fBnano\fP< \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBmicrovolts\fP = \fBmicro\fP< \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBmillivolts\fP = \fBmilli\fP< \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBkilovolts\fP = \fBkilo\fP< \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBmegavolts\fP = \fBmega\fP< \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBgigavolts\fP = \fBgiga\fP< \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBstatvolts\fP = \fBunit\fP< std::ratio< 1000000, 299792458 >, \fBvolts\fP >"
.br
.ti -1c
.RI "using \fBabvolts\fP = \fBunit\fP< std::ratio< 1, 100000000 >, \fBvolts\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBvolt\fP = \fBvolts\fP"
.br
.ti -1c
.RI "using \fBpicovolt\fP = picovolts"
.br
.ti -1c
.RI "using \fBnanovolt\fP = nanovolts"
.br
.ti -1c
.RI "using \fBmicrovolt\fP = microvolts"
.br
.ti -1c
.RI "using \fBmillivolt\fP = millivolts"
.br
.ti -1c
.RI "using \fBkilovolt\fP = kilovolts"
.br
.ti -1c
.RI "using \fBmegavolt\fP = megavolts"
.br
.ti -1c
.RI "using \fBgigavolt\fP = gigavolts"
.br
.ti -1c
.RI "using \fBstatvolt\fP = \fBstatvolts\fP"
.br
.ti -1c
.RI "using \fBabvolt\fP = \fBabvolts\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBvolt_t\fP = \fBunit_t\fP< \fBvolt\fP >"
.br
.ti -1c
.RI "using \fBpicovolt_t\fP = \fBunit_t\fP< picovolt >"
.br
.ti -1c
.RI "using \fBnanovolt_t\fP = \fBunit_t\fP< nanovolt >"
.br
.ti -1c
.RI "using \fBmicrovolt_t\fP = \fBunit_t\fP< microvolt >"
.br
.ti -1c
.RI "using \fBmillivolt_t\fP = \fBunit_t\fP< millivolt >"
.br
.ti -1c
.RI "using \fBkilovolt_t\fP = \fBunit_t\fP< kilovolt >"
.br
.ti -1c
.RI "using \fBmegavolt_t\fP = \fBunit_t\fP< megavolt >"
.br
.ti -1c
.RI "using \fBgigavolt_t\fP = \fBunit_t\fP< gigavolt >"
.br
.ti -1c
.RI "using \fBstatvolt_t\fP = \fBunit_t\fP< \fBstatvolt\fP >"
.br
.ti -1c
.RI "using \fBabvolt_t\fP = \fBunit_t\fP< \fBabvolt\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBV\fP = \fBvolts\fP"
.br
.ti -1c
.RI "using \fBpV\fP = picovolts"
.br
.ti -1c
.RI "using \fBnV\fP = nanovolts"
.br
.ti -1c
.RI "using \fBuV\fP = microvolts"
.br
.ti -1c
.RI "using \fBmV\fP = millivolts"
.br
.ti -1c
.RI "using \fBkV\fP = kilovolts"
.br
.ti -1c
.RI "using \fBMV\fP = megavolts"
.br
.ti -1c
.RI "using \fBGV\fP = gigavolts"
.br
.ti -1c
.RI "using \fBstatV\fP = \fBstatvolts\fP"
.br
.ti -1c
.RI "using \fBabV\fP = \fBabvolts\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing voltage values 

The SI unit for voltage is \fCvolts\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCvoltage_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
