.TH "units::luminous_flux" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::luminous_flux \- namespace for unit types and containers representing \fBluminous_flux\fP values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBlumens\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::luminous_flux_unit\fP >"
.br
.ti -1c
.RI "using \fBpicolumens\fP = \fBpico\fP< \fBlumens\fP >"
.br
.ti -1c
.RI "using \fBnanolumens\fP = \fBnano\fP< \fBlumens\fP >"
.br
.ti -1c
.RI "using \fBmicrolumens\fP = \fBmicro\fP< \fBlumens\fP >"
.br
.ti -1c
.RI "using \fBmillilumens\fP = \fBmilli\fP< \fBlumens\fP >"
.br
.ti -1c
.RI "using \fBkilolumens\fP = \fBkilo\fP< \fBlumens\fP >"
.br
.ti -1c
.RI "using \fBmegalumens\fP = \fBmega\fP< \fBlumens\fP >"
.br
.ti -1c
.RI "using \fBgigalumens\fP = \fBgiga\fP< \fBlumens\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBlumen\fP = \fBlumens\fP"
.br
.ti -1c
.RI "using \fBpicolumen\fP = picolumens"
.br
.ti -1c
.RI "using \fBnanolumen\fP = nanolumens"
.br
.ti -1c
.RI "using \fBmicrolumen\fP = microlumens"
.br
.ti -1c
.RI "using \fBmillilumen\fP = millilumens"
.br
.ti -1c
.RI "using \fBkilolumen\fP = kilolumens"
.br
.ti -1c
.RI "using \fBmegalumen\fP = megalumens"
.br
.ti -1c
.RI "using \fBgigalumen\fP = gigalumens"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBlumen_t\fP = \fBunit_t\fP< \fBlumen\fP >"
.br
.ti -1c
.RI "using \fBpicolumen_t\fP = \fBunit_t\fP< picolumen >"
.br
.ti -1c
.RI "using \fBnanolumen_t\fP = \fBunit_t\fP< nanolumen >"
.br
.ti -1c
.RI "using \fBmicrolumen_t\fP = \fBunit_t\fP< microlumen >"
.br
.ti -1c
.RI "using \fBmillilumen_t\fP = \fBunit_t\fP< millilumen >"
.br
.ti -1c
.RI "using \fBkilolumen_t\fP = \fBunit_t\fP< kilolumen >"
.br
.ti -1c
.RI "using \fBmegalumen_t\fP = \fBunit_t\fP< megalumen >"
.br
.ti -1c
.RI "using \fBgigalumen_t\fP = \fBunit_t\fP< gigalumen >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBlm\fP = \fBlumens\fP"
.br
.ti -1c
.RI "using \fBplm\fP = picolumens"
.br
.ti -1c
.RI "using \fBnlm\fP = nanolumens"
.br
.ti -1c
.RI "using \fBulm\fP = microlumens"
.br
.ti -1c
.RI "using \fBmlm\fP = millilumens"
.br
.ti -1c
.RI "using \fBklm\fP = kilolumens"
.br
.ti -1c
.RI "using \fBMlm\fP = megalumens"
.br
.ti -1c
.RI "using \fBGlm\fP = gigalumens"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing \fBluminous_flux\fP values 

The SI unit for \fBluminous_flux\fP is \fClumens\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCluminous_flux_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
