.TH "units::capacitance" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::capacitance \- namespace for unit types and containers representing capacitance values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBfarads\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::capacitance_unit\fP >"
.br
.ti -1c
.RI "using \fBpicofarads\fP = \fBpico\fP< \fBfarads\fP >"
.br
.ti -1c
.RI "using \fBnanofarads\fP = \fBnano\fP< \fBfarads\fP >"
.br
.ti -1c
.RI "using \fBmicrofarads\fP = \fBmicro\fP< \fBfarads\fP >"
.br
.ti -1c
.RI "using \fBmillifarads\fP = \fBmilli\fP< \fBfarads\fP >"
.br
.ti -1c
.RI "using \fBkilofarads\fP = \fBkilo\fP< \fBfarads\fP >"
.br
.ti -1c
.RI "using \fBmegafarads\fP = \fBmega\fP< \fBfarads\fP >"
.br
.ti -1c
.RI "using \fBgigafarads\fP = \fBgiga\fP< \fBfarads\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBfarad\fP = \fBfarads\fP"
.br
.ti -1c
.RI "using \fBpicofarad\fP = picofarads"
.br
.ti -1c
.RI "using \fBnanofarad\fP = nanofarads"
.br
.ti -1c
.RI "using \fBmicrofarad\fP = microfarads"
.br
.ti -1c
.RI "using \fBmillifarad\fP = millifarads"
.br
.ti -1c
.RI "using \fBkilofarad\fP = kilofarads"
.br
.ti -1c
.RI "using \fBmegafarad\fP = megafarads"
.br
.ti -1c
.RI "using \fBgigafarad\fP = gigafarads"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBF\fP = \fBfarads\fP"
.br
.ti -1c
.RI "using \fBpF\fP = picofarads"
.br
.ti -1c
.RI "using \fBnF\fP = nanofarads"
.br
.ti -1c
.RI "using \fBuF\fP = microfarads"
.br
.ti -1c
.RI "using \fBmF\fP = millifarads"
.br
.ti -1c
.RI "using \fBkF\fP = kilofarads"
.br
.ti -1c
.RI "using \fBMF\fP = megafarads"
.br
.ti -1c
.RI "using \fBGF\fP = gigafarads"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBfarad_t\fP = \fBunit_t\fP< \fBfarad\fP >"
.br
.ti -1c
.RI "using \fBpicofarad_t\fP = \fBunit_t\fP< picofarad >"
.br
.ti -1c
.RI "using \fBnanofarad_t\fP = \fBunit_t\fP< nanofarad >"
.br
.ti -1c
.RI "using \fBmicrofarad_t\fP = \fBunit_t\fP< microfarad >"
.br
.ti -1c
.RI "using \fBmillifarad_t\fP = \fBunit_t\fP< millifarad >"
.br
.ti -1c
.RI "using \fBkilofarad_t\fP = \fBunit_t\fP< kilofarad >"
.br
.ti -1c
.RI "using \fBmegafarad_t\fP = \fBunit_t\fP< megafarad >"
.br
.ti -1c
.RI "using \fBgigafarad_t\fP = \fBunit_t\fP< gigafarad >"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing capacitance values 

The SI unit for capacitance is \fCfarads\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCcapacitance_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
