.TH "units::magnetic_field_strength" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::magnetic_field_strength \- namespace for unit types and containers representing \fBmagnetic_field_strength\fP values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBteslas\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::magnetic_field_strength_unit\fP >"
.br
.ti -1c
.RI "using \fBpicoteslas\fP = \fBpico\fP< \fBteslas\fP >"
.br
.ti -1c
.RI "using \fBnanoteslas\fP = \fBnano\fP< \fBteslas\fP >"
.br
.ti -1c
.RI "using \fBmicroteslas\fP = \fBmicro\fP< \fBteslas\fP >"
.br
.ti -1c
.RI "using \fBmilliteslas\fP = \fBmilli\fP< \fBteslas\fP >"
.br
.ti -1c
.RI "using \fBkiloteslas\fP = \fBkilo\fP< \fBteslas\fP >"
.br
.ti -1c
.RI "using \fBmegateslas\fP = \fBmega\fP< \fBteslas\fP >"
.br
.ti -1c
.RI "using \fBgigateslas\fP = \fBgiga\fP< \fBteslas\fP >"
.br
.ti -1c
.RI "using \fBgauss\fP = \fBcompound_unit\fP< \fBmagnetic_flux::maxwell\fP, \fBinverse\fP< \fBsquared\fP< length::centimeter >>>"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBtesla\fP = \fBteslas\fP"
.br
.ti -1c
.RI "using \fBpicotesla\fP = picoteslas"
.br
.ti -1c
.RI "using \fBnanotesla\fP = nanoteslas"
.br
.ti -1c
.RI "using \fBmicrotesla\fP = microteslas"
.br
.ti -1c
.RI "using \fBmillitesla\fP = milliteslas"
.br
.ti -1c
.RI "using \fBkilotesla\fP = kiloteslas"
.br
.ti -1c
.RI "using \fBmegatesla\fP = megateslas"
.br
.ti -1c
.RI "using \fBgigatesla\fP = gigateslas"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBtesla_t\fP = \fBunit_t\fP< \fBtesla\fP >"
.br
.ti -1c
.RI "using \fBpicotesla_t\fP = \fBunit_t\fP< picotesla >"
.br
.ti -1c
.RI "using \fBnanotesla_t\fP = \fBunit_t\fP< nanotesla >"
.br
.ti -1c
.RI "using \fBmicrotesla_t\fP = \fBunit_t\fP< microtesla >"
.br
.ti -1c
.RI "using \fBmillitesla_t\fP = \fBunit_t\fP< millitesla >"
.br
.ti -1c
.RI "using \fBkilotesla_t\fP = \fBunit_t\fP< kilotesla >"
.br
.ti -1c
.RI "using \fBmegatesla_t\fP = \fBunit_t\fP< megatesla >"
.br
.ti -1c
.RI "using \fBgigatesla_t\fP = \fBunit_t\fP< gigatesla >"
.br
.ti -1c
.RI "using \fBgauss_t\fP = \fBunit_t\fP< gauss >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBT\fP = \fBteslas\fP"
.br
.ti -1c
.RI "using \fBpT\fP = picoteslas"
.br
.ti -1c
.RI "using \fBnT\fP = nanoteslas"
.br
.ti -1c
.RI "using \fBuT\fP = microteslas"
.br
.ti -1c
.RI "using \fBmT\fP = milliteslas"
.br
.ti -1c
.RI "using \fBkT\fP = kiloteslas"
.br
.ti -1c
.RI "using \fBMT\fP = megateslas"
.br
.ti -1c
.RI "using \fBGT\fP = gigateslas"
.br
.ti -1c
.RI "using \fBG\fP = gauss"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing \fBmagnetic_field_strength\fP values 

The SI unit for \fBmagnetic_field_strength\fP is \fCteslas\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCmagnetic_field_strength_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
