.TH "units::radiation" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::radiation \- namespace for unit types and containers representing radiation values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBbecquerels\fP = \fBinverse\fP< \fBtime::seconds\fP >"
.br
.ti -1c
.RI "using \fBpicobecquerels\fP = \fBpico\fP< becquerels >"
.br
.ti -1c
.RI "using \fBnanobecquerels\fP = \fBnano\fP< becquerels >"
.br
.ti -1c
.RI "using \fBmicrobecquerels\fP = \fBmicro\fP< becquerels >"
.br
.ti -1c
.RI "using \fBmillibecquerels\fP = \fBmilli\fP< becquerels >"
.br
.ti -1c
.RI "using \fBkilobecquerels\fP = \fBkilo\fP< becquerels >"
.br
.ti -1c
.RI "using \fBmegabecquerels\fP = \fBmega\fP< becquerels >"
.br
.ti -1c
.RI "using \fBgigabecquerels\fP = \fBgiga\fP< becquerels >"
.br
.ti -1c
.RI "using \fBgrays\fP = \fBcompound_unit\fP< \fBenergy::joules\fP, \fBinverse\fP< \fBmass::kilogram\fP >>"
.br
.ti -1c
.RI "using \fBpicograys\fP = \fBpico\fP< grays >"
.br
.ti -1c
.RI "using \fBnanograys\fP = \fBnano\fP< grays >"
.br
.ti -1c
.RI "using \fBmicrograys\fP = \fBmicro\fP< grays >"
.br
.ti -1c
.RI "using \fBmilligrays\fP = \fBmilli\fP< grays >"
.br
.ti -1c
.RI "using \fBkilograys\fP = \fBkilo\fP< grays >"
.br
.ti -1c
.RI "using \fBmegagrays\fP = \fBmega\fP< grays >"
.br
.ti -1c
.RI "using \fBgigagrays\fP = \fBgiga\fP< grays >"
.br
.ti -1c
.RI "using \fBsieverts\fP = \fBcompound_unit\fP< \fBenergy::joules\fP, \fBinverse\fP< \fBmass::kilogram\fP >>"
.br
.ti -1c
.RI "using \fBpicosieverts\fP = \fBpico\fP< sieverts >"
.br
.ti -1c
.RI "using \fBnanosieverts\fP = \fBnano\fP< sieverts >"
.br
.ti -1c
.RI "using \fBmicrosieverts\fP = \fBmicro\fP< sieverts >"
.br
.ti -1c
.RI "using \fBmillisieverts\fP = \fBmilli\fP< sieverts >"
.br
.ti -1c
.RI "using \fBkilosieverts\fP = \fBkilo\fP< sieverts >"
.br
.ti -1c
.RI "using \fBmegasieverts\fP = \fBmega\fP< sieverts >"
.br
.ti -1c
.RI "using \fBgigasieverts\fP = \fBgiga\fP< sieverts >"
.br
.ti -1c
.RI "using \fBcuries\fP = \fBunit\fP< std::ratio< 37 >, gigabecquerels >"
.br
.ti -1c
.RI "using \fBrutherfords\fP = megabecquerels"
.br
.ti -1c
.RI "using \fBrads\fP = \fBunit\fP< std::ratio< 1, 100 >, grays >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBbecquerel\fP = becquerels"
.br
.ti -1c
.RI "using \fBpicobecquerel\fP = picobecquerels"
.br
.ti -1c
.RI "using \fBnanobecquerel\fP = nanobecquerels"
.br
.ti -1c
.RI "using \fBmicrobecquerel\fP = microbecquerels"
.br
.ti -1c
.RI "using \fBmillibecquerel\fP = millibecquerels"
.br
.ti -1c
.RI "using \fBkilobecquerel\fP = kilobecquerels"
.br
.ti -1c
.RI "using \fBmegabecquerel\fP = megabecquerels"
.br
.ti -1c
.RI "using \fBgigabecquerel\fP = gigabecquerels"
.br
.ti -1c
.RI "using \fBgray\fP = grays"
.br
.ti -1c
.RI "using \fBpicogray\fP = picograys"
.br
.ti -1c
.RI "using \fBnanogray\fP = nanograys"
.br
.ti -1c
.RI "using \fBmicrogray\fP = micrograys"
.br
.ti -1c
.RI "using \fBmilligray\fP = milligrays"
.br
.ti -1c
.RI "using \fBkilogray\fP = kilograys"
.br
.ti -1c
.RI "using \fBmegagray\fP = megagrays"
.br
.ti -1c
.RI "using \fBgigagray\fP = gigagrays"
.br
.ti -1c
.RI "using \fBsievert\fP = sieverts"
.br
.ti -1c
.RI "using \fBpicosievert\fP = picosieverts"
.br
.ti -1c
.RI "using \fBnanosievert\fP = nanosieverts"
.br
.ti -1c
.RI "using \fBmicrosievert\fP = microsieverts"
.br
.ti -1c
.RI "using \fBmillisievert\fP = millisieverts"
.br
.ti -1c
.RI "using \fBkilosievert\fP = kilosieverts"
.br
.ti -1c
.RI "using \fBmegasievert\fP = megasieverts"
.br
.ti -1c
.RI "using \fBgigasievert\fP = gigasieverts"
.br
.ti -1c
.RI "using \fBcurie\fP = \fBcuries\fP"
.br
.ti -1c
.RI "using \fBrutherford\fP = rutherfords"
.br
.ti -1c
.RI "using \fBrad\fP = \fBrads\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBbecquerel_t\fP = \fBunit_t\fP< becquerel >"
.br
.ti -1c
.RI "using \fBpicobecquerel_t\fP = \fBunit_t\fP< picobecquerel >"
.br
.ti -1c
.RI "using \fBnanobecquerel_t\fP = \fBunit_t\fP< nanobecquerel >"
.br
.ti -1c
.RI "using \fBmicrobecquerel_t\fP = \fBunit_t\fP< microbecquerel >"
.br
.ti -1c
.RI "using \fBmillibecquerel_t\fP = \fBunit_t\fP< millibecquerel >"
.br
.ti -1c
.RI "using \fBkilobecquerel_t\fP = \fBunit_t\fP< kilobecquerel >"
.br
.ti -1c
.RI "using \fBmegabecquerel_t\fP = \fBunit_t\fP< megabecquerel >"
.br
.ti -1c
.RI "using \fBgigabecquerel_t\fP = \fBunit_t\fP< gigabecquerel >"
.br
.ti -1c
.RI "using \fBgray_t\fP = \fBunit_t\fP< gray >"
.br
.ti -1c
.RI "using \fBpicogray_t\fP = \fBunit_t\fP< picogray >"
.br
.ti -1c
.RI "using \fBnanogray_t\fP = \fBunit_t\fP< nanogray >"
.br
.ti -1c
.RI "using \fBmicrogray_t\fP = \fBunit_t\fP< microgray >"
.br
.ti -1c
.RI "using \fBmilligray_t\fP = \fBunit_t\fP< milligray >"
.br
.ti -1c
.RI "using \fBkilogray_t\fP = \fBunit_t\fP< kilogray >"
.br
.ti -1c
.RI "using \fBmegagray_t\fP = \fBunit_t\fP< megagray >"
.br
.ti -1c
.RI "using \fBgigagray_t\fP = \fBunit_t\fP< gigagray >"
.br
.ti -1c
.RI "using \fBsievert_t\fP = \fBunit_t\fP< sievert >"
.br
.ti -1c
.RI "using \fBpicosievert_t\fP = \fBunit_t\fP< picosievert >"
.br
.ti -1c
.RI "using \fBnanosievert_t\fP = \fBunit_t\fP< nanosievert >"
.br
.ti -1c
.RI "using \fBmicrosievert_t\fP = \fBunit_t\fP< microsievert >"
.br
.ti -1c
.RI "using \fBmillisievert_t\fP = \fBunit_t\fP< millisievert >"
.br
.ti -1c
.RI "using \fBkilosievert_t\fP = \fBunit_t\fP< kilosievert >"
.br
.ti -1c
.RI "using \fBmegasievert_t\fP = \fBunit_t\fP< megasievert >"
.br
.ti -1c
.RI "using \fBgigasievert_t\fP = \fBunit_t\fP< gigasievert >"
.br
.ti -1c
.RI "using \fBcurie_t\fP = \fBunit_t\fP< \fBcurie\fP >"
.br
.ti -1c
.RI "using \fBrutherford_t\fP = \fBunit_t\fP< rutherford >"
.br
.ti -1c
.RI "using \fBrad_t\fP = \fBunit_t\fP< \fBrad\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBBq\fP = becquerels"
.br
.ti -1c
.RI "using \fBpBq\fP = picobecquerels"
.br
.ti -1c
.RI "using \fBnBq\fP = nanobecquerels"
.br
.ti -1c
.RI "using \fBuBq\fP = microbecquerels"
.br
.ti -1c
.RI "using \fBmBq\fP = millibecquerels"
.br
.ti -1c
.RI "using \fBkBq\fP = kilobecquerels"
.br
.ti -1c
.RI "using \fBMBq\fP = megabecquerels"
.br
.ti -1c
.RI "using \fBGBq\fP = gigabecquerels"
.br
.ti -1c
.RI "using \fBGy\fP = grays"
.br
.ti -1c
.RI "using \fBpGy\fP = picograys"
.br
.ti -1c
.RI "using \fBnGy\fP = nanograys"
.br
.ti -1c
.RI "using \fBuGy\fP = micrograys"
.br
.ti -1c
.RI "using \fBmGy\fP = milligrays"
.br
.ti -1c
.RI "using \fBkGy\fP = kilograys"
.br
.ti -1c
.RI "using \fBMGy\fP = megagrays"
.br
.ti -1c
.RI "using \fBGGy\fP = gigagrays"
.br
.ti -1c
.RI "using \fBSv\fP = sieverts"
.br
.ti -1c
.RI "using \fBpSv\fP = picosieverts"
.br
.ti -1c
.RI "using \fBnSv\fP = nanosieverts"
.br
.ti -1c
.RI "using \fBuSv\fP = microsieverts"
.br
.ti -1c
.RI "using \fBmSv\fP = millisieverts"
.br
.ti -1c
.RI "using \fBkSv\fP = kilosieverts"
.br
.ti -1c
.RI "using \fBMSv\fP = megasieverts"
.br
.ti -1c
.RI "using \fBGSv\fP = gigasieverts"
.br
.ti -1c
.RI "using \fBCi\fP = \fBcuries\fP"
.br
.ti -1c
.RI "using \fBrd\fP = rutherfords"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing radiation values 

The SI units for radiation are:
.IP "\(bu" 2
source activity: becquerel
.IP "\(bu" 2
absorbed dose: gray
.IP "\(bu" 2
equivalent dose: sievert 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
