.TH "units::force" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::force \- namespace for unit types and containers representing force values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBnewtons\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::force_unit\fP >"
.br
.ti -1c
.RI "using \fBpounds\fP = \fBcompound_unit\fP< \fBmass::slug\fP, \fBlength::foot\fP, \fBinverse\fP< \fBsquared\fP< \fBtime::seconds\fP >>>"
.br
.ti -1c
.RI "using \fBdynes\fP = \fBunit\fP< std::ratio< 1, 100000 >, \fBnewtons\fP >"
.br
.ti -1c
.RI "using \fBkiloponds\fP = \fBcompound_unit\fP< \fBacceleration::standard_gravity\fP, \fBmass::kilograms\fP >"
.br
.ti -1c
.RI "using \fBpoundals\fP = \fBcompound_unit\fP< \fBmass::pound\fP, \fBlength::foot\fP, \fBinverse\fP< \fBsquared\fP< \fBtime::seconds\fP >>>"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBnewton\fP = \fBnewtons\fP"
.br
.ti -1c
.RI "using \fBpound\fP = pounds"
.br
.ti -1c
.RI "using \fBdyne\fP = \fBdynes\fP"
.br
.ti -1c
.RI "using \fBkilopond\fP = kiloponds"
.br
.ti -1c
.RI "using \fBpoundal\fP = poundals"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBN\fP = \fBnewtons\fP"
.br
.ti -1c
.RI "using \fBlbf\fP = pounds"
.br
.ti -1c
.RI "using \fBdyn\fP = \fBdynes\fP"
.br
.ti -1c
.RI "using \fBkp\fP = kiloponds"
.br
.ti -1c
.RI "using \fBpdl\fP = poundals"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBnewton_t\fP = \fBunit_t\fP< \fBnewton\fP >"
.br
.ti -1c
.RI "using \fBpound_t\fP = \fBunit_t\fP< pound >"
.br
.ti -1c
.RI "using \fBdyne_t\fP = \fBunit_t\fP< \fBdyne\fP >"
.br
.ti -1c
.RI "using \fBkilopond_t\fP = \fBunit_t\fP< kilopond >"
.br
.ti -1c
.RI "using \fBpoundal_t\fP = \fBunit_t\fP< poundal >"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing force values 

The SI unit for force is \fCnewtons\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCforce_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
