.TH "units::unit_value_sqrt< U1, Eps >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::unit_value_sqrt< U1, Eps > \- calculates square root of \fBunit_value_t\fP at compile-time  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.PP
Inherits unit_value_arithmetic< U1, U1 >, and _unit_value_t< square_root< traits::unit_value_t_traits< U1 >::unit_type, Eps > >\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBunit_t\fP< unit_type > \fBvalue\fP ()"
.br
.RI "\fIValue of square root\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class U1, std::intmax_t Eps = 10000000000>struct units::unit_value_sqrt< U1, Eps >"
calculates square root of \fBunit_value_t\fP at compile-time 

The resulting unit will the square root \fCunit_type\fP of \fCU1\fP 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIU1\fP \fC\fBunit_value_t\fP\fP to take the square root of\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
unit_value_t_traits to access information about the properties of the class, such as it's \fBunit\fP type and rational \fBvalue\fP\&. 
.RE
.PP
\fBNote:\fP
.RS 4
very similar in concept to \fC\fBunits::ratio_sqrt\fP\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class U1 , std::intmax_t Eps = 10000000000> static const \fBunit_t\fP<unit_type> \fBunits::unit_value_sqrt\fP< U1, Eps >::value ()\fC [inline]\fP, \fC [static]\fP"

.PP
Value of square root\&. Returns the calculated value of the square root of \fCU1\fP, in units of \fCU1^1/2\fP\&. 
.PP
\fBReturns:\fP
.RS 4
Value of the square root in the appropriate units\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
