.TH "units::linear_scale< T >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::linear_scale< T > \- \fBunit_t\fP scale which is linear  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlinear_scale\fP ()"
.br
.RI "\fIdefault constructor\&. \fP"
.ti -1c
.RI "\fBlinear_scale\fP (T value)"
.br
.RI "\fIconstructor\&. \fP"
.ti -1c
.RI "T \fBoperator()\fP () const "
.br
.RI "\fIreturns value\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBm_value\fP"
.br
.RI "\fIlinearized value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct units::linear_scale< T >"
\fBunit_t\fP scale which is linear 

Represents units on a linear scale\&. This is the appropriate \fBunit_t\fP scale for almost all units almost all of the time\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP underlying storage type 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBunit_t\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
