.TH "units::angle" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::angle \- namespace for unit types and containers representing angle values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBradians\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::angle_unit\fP >"
.br
.ti -1c
.RI "using \fBmilliradians\fP = \fBmilli\fP< \fBradians\fP >"
.br
.ti -1c
.RI "using \fBdegrees\fP = \fBunit\fP< std::ratio< 1, 180 >, \fBradians\fP, std::ratio< 1 >>"
.br
.ti -1c
.RI "using \fBarcminutes\fP = \fBunit\fP< std::ratio< 1, 60 >, \fBdegrees\fP >"
.br
.ti -1c
.RI "using \fBarcseconds\fP = \fBunit\fP< std::ratio< 1, 60 >, \fBarcminutes\fP >"
.br
.ti -1c
.RI "using \fBmilliarcseconds\fP = \fBmilli\fP< \fBarcseconds\fP >"
.br
.ti -1c
.RI "using \fBturns\fP = \fBunit\fP< std::ratio< 2 >, \fBradians\fP, std::ratio< 1 >>"
.br
.ti -1c
.RI "using \fBmils\fP = \fBunit\fP< std::ratio< 1, 6400 >, \fBradians\fP >"
.br
.ti -1c
.RI "using \fBgradians\fP = \fBunit\fP< std::ratio< 1, 400 >, \fBturns\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBradian\fP = \fBradians\fP"
.br
.ti -1c
.RI "using \fBmilliradian\fP = milliradians"
.br
.ti -1c
.RI "using \fBdegree\fP = \fBdegrees\fP"
.br
.ti -1c
.RI "using \fBarcminute\fP = \fBarcminutes\fP"
.br
.ti -1c
.RI "using \fBarcsecond\fP = \fBarcseconds\fP"
.br
.ti -1c
.RI "using \fBmilliarcsecond\fP = milliarcseconds"
.br
.ti -1c
.RI "using \fBturn\fP = \fBturns\fP"
.br
.ti -1c
.RI "using \fBmil\fP = \fBmils\fP"
.br
.ti -1c
.RI "using \fBgradian\fP = \fBgradians\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBrad\fP = \fBradians\fP"
.br
.ti -1c
.RI "using \fBmrad\fP = milliradians"
.br
.ti -1c
.RI "using \fBdeg\fP = \fBdegrees\fP"
.br
.ti -1c
.RI "using \fBmin\fP = \fBarcminutes\fP"
.br
.ti -1c
.RI "using \fBsec\fP = \fBarcseconds\fP"
.br
.ti -1c
.RI "using \fBmas\fP = milliarcseconds"
.br
.ti -1c
.RI "using \fBtr\fP = \fBturn\fP"
.br
.ti -1c
.RI "using \fBgon\fP = \fBgradians\fP"
.br
.ti -1c
.RI "using \fBgrad\fP = \fBgradians\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBradian_t\fP = \fBunit_t\fP< \fBradian\fP >"
.br
.ti -1c
.RI "using \fBmilliradian_t\fP = \fBunit_t\fP< milliradian >"
.br
.ti -1c
.RI "using \fBdegree_t\fP = \fBunit_t\fP< \fBdegree\fP >"
.br
.ti -1c
.RI "using \fBminute_t\fP = \fBunit_t\fP< \fBarcminute\fP >"
.br
.ti -1c
.RI "using \fBsecond_t\fP = \fBunit_t\fP< \fBarcsecond\fP >"
.br
.ti -1c
.RI "using \fBturn_t\fP = \fBunit_t\fP< \fBturn\fP >"
.br
.ti -1c
.RI "using \fBmil_t\fP = \fBunit_t\fP< \fBmil\fP >"
.br
.ti -1c
.RI "using \fBgradian_t\fP = \fBunit_t\fP< \fBgradian\fP >"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing angle values 

The SI unit for angle is \fCradians\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCangle_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
