.TH "units::illuminance" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::illuminance \- namespace for unit types and containers representing illuminance values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBluxes\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::illuminance_unit\fP >"
.br
.ti -1c
.RI "using \fBpicoluxes\fP = \fBpico\fP< \fBluxes\fP >"
.br
.ti -1c
.RI "using \fBnanoluxes\fP = \fBnano\fP< \fBluxes\fP >"
.br
.ti -1c
.RI "using \fBmicroluxes\fP = \fBmicro\fP< \fBluxes\fP >"
.br
.ti -1c
.RI "using \fBmilliluxes\fP = \fBmilli\fP< \fBluxes\fP >"
.br
.ti -1c
.RI "using \fBkiloluxes\fP = \fBkilo\fP< \fBluxes\fP >"
.br
.ti -1c
.RI "using \fBmegaluxes\fP = \fBmega\fP< \fBluxes\fP >"
.br
.ti -1c
.RI "using \fBgigaluxes\fP = \fBgiga\fP< \fBluxes\fP >"
.br
.ti -1c
.RI "using \fBfootcandles\fP = \fBcompound_unit\fP< \fBluminous_flux::lumen\fP, \fBinverse\fP< \fBsquared\fP< \fBlength::foot\fP >>>"
.br
.ti -1c
.RI "using \fBlumens_per_square_inch\fP = \fBcompound_unit\fP< \fBluminous_flux::lumen\fP, \fBinverse\fP< \fBsquared\fP< \fBlength::inch\fP >>>"
.br
.ti -1c
.RI "using \fBphots\fP = \fBcompound_unit\fP< \fBluminous_flux::lumens\fP, \fBinverse\fP< \fBsquared\fP< length::centimeter >>>"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBlux\fP = \fBluxes\fP"
.br
.ti -1c
.RI "using \fBpicolux\fP = picoluxes"
.br
.ti -1c
.RI "using \fBnanolux\fP = nanoluxes"
.br
.ti -1c
.RI "using \fBmicrolux\fP = microluxes"
.br
.ti -1c
.RI "using \fBmillilux\fP = milliluxes"
.br
.ti -1c
.RI "using \fBkilolux\fP = kiloluxes"
.br
.ti -1c
.RI "using \fBmegalux\fP = megaluxes"
.br
.ti -1c
.RI "using \fBgigalux\fP = gigaluxes"
.br
.ti -1c
.RI "using \fBfootcandle\fP = footcandles"
.br
.ti -1c
.RI "using \fBphot\fP = phots"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBlux_t\fP = \fBunit_t\fP< \fBlux\fP >"
.br
.ti -1c
.RI "using \fBpicolux_t\fP = \fBunit_t\fP< picolux >"
.br
.ti -1c
.RI "using \fBnanolux_t\fP = \fBunit_t\fP< nanolux >"
.br
.ti -1c
.RI "using \fBmicrolux_t\fP = \fBunit_t\fP< microlux >"
.br
.ti -1c
.RI "using \fBmillilux_t\fP = \fBunit_t\fP< millilux >"
.br
.ti -1c
.RI "using \fBkilolux_t\fP = \fBunit_t\fP< kilolux >"
.br
.ti -1c
.RI "using \fBmegalux_t\fP = \fBunit_t\fP< megalux >"
.br
.ti -1c
.RI "using \fBgigalux_t\fP = \fBunit_t\fP< gigalux >"
.br
.ti -1c
.RI "using \fBfootcandle_t\fP = \fBunit_t\fP< footcandle >"
.br
.ti -1c
.RI "using \fBlumens_per_square_inch_t\fP = \fBunit_t\fP< lumens_per_square_inch >"
.br
.ti -1c
.RI "using \fBphot_t\fP = \fBunit_t\fP< phot >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBlx\fP = \fBluxes\fP"
.br
.ti -1c
.RI "using \fBplx\fP = picoluxes"
.br
.ti -1c
.RI "using \fBnlx\fP = nanoluxes"
.br
.ti -1c
.RI "using \fBulx\fP = microluxes"
.br
.ti -1c
.RI "using \fBmlx\fP = milliluxes"
.br
.ti -1c
.RI "using \fBklx\fP = kiloluxes"
.br
.ti -1c
.RI "using \fBMlx\fP = megaluxes"
.br
.ti -1c
.RI "using \fBGlx\fP = gigaluxes"
.br
.ti -1c
.RI "using \fBfc\fP = footcandles"
.br
.ti -1c
.RI "using \fBph\fP = phots"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing illuminance values 

The SI unit for illuminance is \fCluxes\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCilluminance_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
