.TH "units::traits::is_energy_unit< T >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::traits::is_energy_unit< T > \- Trait which tests whether a type represents a unit of energy\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.PP
Inherits integral_constant< bool, all_true< detail::is_energy_unit_impl< std::decay< T >::type >::value\&.\&.\&.>::value >\&.
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&. T>struct units::traits::is_energy_unit< T >"
Trait which tests whether a type represents a unit of energy\&. 

Inherits from \fCstd::true_type\fP or \fCstd::false_type\fP\&. Use \fC\fBis_energy_unit\fP<T>::value\fP to test the unit represents a energy quantity\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP one or more types to test 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
