.TH "units::impedance" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::impedance \- namespace for unit types and containers representing impedance values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBohms\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::impedance_unit\fP >"
.br
.ti -1c
.RI "using \fBpicoohms\fP = \fBpico\fP< \fBohms\fP >"
.br
.ti -1c
.RI "using \fBnanoohms\fP = \fBnano\fP< \fBohms\fP >"
.br
.ti -1c
.RI "using \fBmicroohms\fP = \fBmicro\fP< \fBohms\fP >"
.br
.ti -1c
.RI "using \fBmilliohms\fP = \fBmilli\fP< \fBohms\fP >"
.br
.ti -1c
.RI "using \fBkiloohms\fP = \fBkilo\fP< \fBohms\fP >"
.br
.ti -1c
.RI "using \fBmegaohms\fP = \fBmega\fP< \fBohms\fP >"
.br
.ti -1c
.RI "using \fBgigaohms\fP = \fBgiga\fP< \fBohms\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBohm\fP = \fBohms\fP"
.br
.ti -1c
.RI "using \fBpicoohm\fP = picoohms"
.br
.ti -1c
.RI "using \fBnanoohm\fP = nanoohms"
.br
.ti -1c
.RI "using \fBmicroohm\fP = microohms"
.br
.ti -1c
.RI "using \fBmilliohm\fP = milliohms"
.br
.ti -1c
.RI "using \fBkiloohm\fP = kiloohms"
.br
.ti -1c
.RI "using \fBmegaohm\fP = megaohms"
.br
.ti -1c
.RI "using \fBgigaohm\fP = gigaohms"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBohm_t\fP = \fBunit_t\fP< \fBohm\fP >"
.br
.ti -1c
.RI "using \fBpicoohm_t\fP = \fBunit_t\fP< picoohm >"
.br
.ti -1c
.RI "using \fBnanoohm_t\fP = \fBunit_t\fP< nanoohm >"
.br
.ti -1c
.RI "using \fBmicroohm_t\fP = \fBunit_t\fP< microohm >"
.br
.ti -1c
.RI "using \fBmilliohm_t\fP = \fBunit_t\fP< milliohm >"
.br
.ti -1c
.RI "using \fBkiloohm_t\fP = \fBunit_t\fP< kiloohm >"
.br
.ti -1c
.RI "using \fBmegaohm_t\fP = \fBunit_t\fP< megaohm >"
.br
.ti -1c
.RI "using \fBgigaohm_t\fP = \fBunit_t\fP< gigaohm >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBOhm\fP = \fBohms\fP"
.br
.ti -1c
.RI "using \fBpOhm\fP = picoohms"
.br
.ti -1c
.RI "using \fBnOhm\fP = nanoohms"
.br
.ti -1c
.RI "using \fBuOhm\fP = microohms"
.br
.ti -1c
.RI "using \fBmOhm\fP = milliohms"
.br
.ti -1c
.RI "using \fBkOhm\fP = kiloohms"
.br
.ti -1c
.RI "using \fBMOhm\fP = megaohms"
.br
.ti -1c
.RI "using \fBGOhm\fP = gigaohms"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing impedance values 

The SI unit for impedance is \fCohms\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCimpedance_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
