.TH "units::traits::is_base_unit< T >" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::traits::is_base_unit< T > \- Trait which tests if a class is a \fC\fBbase_unit\fP\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <units\&.h>\fP
.PP
Inherits is_base_of< detail::_base_unit_t, T >\&.
.SH "Detailed Description"
.PP 

.SS "template<class T>struct units::traits::is_base_unit< T >"
Trait which tests if a class is a \fC\fBbase_unit\fP\fP type\&. 

Inherits from \fCstd::true_type\fP or \fCstd::false_type\fP\&. Use \fC\fBis_base_unit\fP<T>::value\fP to test whether \fCclass T\fP implements a \fC\fBbase_unit\fP\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
