.TH "units::category" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::category \- namespace representing the implemented base and derived unit types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBscalar_unit\fP = \fBbase_unit\fP<>"
.br
.RI "\fIRepresents a quantity with no dimension\&. \fP"
.ti -1c
.RI "using \fBdimensionless_unit\fP = \fBbase_unit\fP<>"
.br
.RI "\fIRepresents a quantity with no dimension\&. \fP"
.ti -1c
.RI "using \fBlength_unit\fP = \fBbase_unit\fP< std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of length\&. \fP"
.ti -1c
.RI "using \fBmass_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of mass\&. \fP"
.ti -1c
.RI "using \fBtime_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of time\&. \fP"
.ti -1c
.RI "using \fBangle_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of angle\&. \fP"
.ti -1c
.RI "using \fBcurrent_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of current\&. \fP"
.ti -1c
.RI "using \fBtemperature_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of temperature\&. \fP"
.ti -1c
.RI "using \fBsubstance_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of amount of substance\&. \fP"
.ti -1c
.RI "using \fBluminous_intensity_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI base unit of luminous intensity\&. \fP"
.ti -1c
.RI "using \fBsolid_angle_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 2 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >>"
.br
.RI "\fIRepresents an SI derived unit of solid angle\&. \fP"
.ti -1c
.RI "using \fBfrequency_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio<-1 >>"
.br
.RI "\fIRepresents an SI derived unit of frequency\&. \fP"
.ti -1c
.RI "using \fBvelocity_unit\fP = \fBbase_unit\fP< std::ratio< 1 >, std::ratio< 0 >, std::ratio<-1 >>"
.br
.RI "\fIRepresents an SI derived unit of velocity\&. \fP"
.ti -1c
.RI "using \fBangular_velocity_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio<-1 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI derived unit of angular velocity\&. \fP"
.ti -1c
.RI "using \fBacceleration_unit\fP = \fBbase_unit\fP< std::ratio< 1 >, std::ratio< 0 >, std::ratio<-2 >>"
.br
.RI "\fIRepresents an SI derived unit of acceleration\&. \fP"
.ti -1c
.RI "using \fBforce_unit\fP = \fBbase_unit\fP< std::ratio< 1 >, std::ratio< 1 >, std::ratio<-2 >>"
.br
.RI "\fIRepresents an SI derived unit of force\&. \fP"
.ti -1c
.RI "using \fBpressure_unit\fP = \fBbase_unit\fP< std::ratio<-1 >, std::ratio< 1 >, std::ratio<-2 >>"
.br
.RI "\fIRepresents an SI derived unit of pressure\&. \fP"
.ti -1c
.RI "using \fBcharge_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI derived unit of charge\&. \fP"
.ti -1c
.RI "using \fBenergy_unit\fP = \fBbase_unit\fP< std::ratio< 2 >, std::ratio< 1 >, std::ratio<-2 >>"
.br
.RI "\fIRepresents an SI derived unit of energy\&. \fP"
.ti -1c
.RI "using \fBpower_unit\fP = \fBbase_unit\fP< std::ratio< 2 >, std::ratio< 1 >, std::ratio<-3 >>"
.br
.RI "\fIRepresents an SI derived unit of power\&. \fP"
.ti -1c
.RI "using \fBvoltage_unit\fP = \fBbase_unit\fP< std::ratio< 2 >, std::ratio< 1 >, std::ratio<-3 >, std::ratio< 0 >, std::ratio<-1 >>"
.br
.RI "\fIRepresents an SI derived unit of voltage\&. \fP"
.ti -1c
.RI "using \fBcapacitance_unit\fP = \fBbase_unit\fP< std::ratio<-2 >, std::ratio<-1 >, std::ratio< 4 >, std::ratio< 0 >, std::ratio< 2 >>"
.br
.RI "\fIRepresents an SI derived unit of capacitance\&. \fP"
.ti -1c
.RI "using \fBimpedance_unit\fP = \fBbase_unit\fP< std::ratio< 2 >, std::ratio< 1 >, std::ratio<-3 >, std::ratio< 0 >, std::ratio<-2 >>"
.br
.RI "\fIRepresents an SI derived unit of impedance\&. \fP"
.ti -1c
.RI "using \fBconductance_unit\fP = \fBbase_unit\fP< std::ratio<-2 >, std::ratio<-1 >, std::ratio< 3 >, std::ratio< 0 >, std::ratio< 2 >>"
.br
.RI "\fIRepresents an SI derived unit of conductance\&. \fP"
.ti -1c
.RI "using \fBmagnetic_flux_unit\fP = \fBbase_unit\fP< std::ratio< 2 >, std::ratio< 1 >, std::ratio<-2 >, std::ratio< 0 >, std::ratio<-1 >>"
.br
.RI "\fIRepresents an SI derived unit of magnetic flux\&. \fP"
.ti -1c
.RI "using \fBmagnetic_field_strength_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 1 >, std::ratio<-2 >, std::ratio< 0 >, std::ratio<-1 >>"
.br
.RI "\fIRepresents an SI derived unit of magnetic field strength\&. \fP"
.ti -1c
.RI "using \fBinductance_unit\fP = \fBbase_unit\fP< std::ratio< 2 >, std::ratio< 1 >, std::ratio<-2 >, std::ratio< 0 >, std::ratio<-2 >>"
.br
.RI "\fIRepresents an SI derived unit of inductance\&. \fP"
.ti -1c
.RI "using \fBluminous_flux_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 2 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI derived unit of luminous flux\&. \fP"
.ti -1c
.RI "using \fBilluminance_unit\fP = \fBbase_unit\fP< std::ratio<-2 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 2 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 0 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI derived unit of illuminance\&. \fP"
.ti -1c
.RI "using \fBradioactivity_unit\fP = \fBbase_unit\fP< std::ratio< 0 >, std::ratio< 0 >, std::ratio<-1 >>"
.br
.RI "\fIRepresents an SI derived unit of radioactivity\&. \fP"
.ti -1c
.RI "using \fBtorque_unit\fP = \fBbase_unit\fP< std::ratio< 2 >, std::ratio< 1 >, std::ratio<-2 >>"
.br
.RI "\fIRepresents an SI derived unit of torque\&. \fP"
.ti -1c
.RI "using \fBarea_unit\fP = \fBbase_unit\fP< std::ratio< 2 >>"
.br
.RI "\fIRepresents an SI derived unit of area\&. \fP"
.ti -1c
.RI "using \fBvolume_unit\fP = \fBbase_unit\fP< std::ratio< 3 >>"
.br
.RI "\fIRepresents an SI derived unit of volume\&. \fP"
.ti -1c
.RI "using \fBdensity_unit\fP = \fBbase_unit\fP< std::ratio<-3 >, std::ratio< 1 >>"
.br
.RI "\fIRepresents an SI derived unit of density\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
namespace representing the implemented base and derived unit types\&. 

These will not generally be needed by library users\&. 
.PP
\fBSee also:\fP
.RS 4
\fBbase_unit\fP for the definition of the \fBcategory\fP prarameters\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
