.TH "units::magnetic_flux" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::magnetic_flux \- namespace for unit types and containers representing \fBmagnetic_flux\fP values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBwebers\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::magnetic_flux_unit\fP >"
.br
.ti -1c
.RI "using \fBpicowebers\fP = \fBpico\fP< \fBwebers\fP >"
.br
.ti -1c
.RI "using \fBnanowebers\fP = \fBnano\fP< \fBwebers\fP >"
.br
.ti -1c
.RI "using \fBmicrowebers\fP = \fBmicro\fP< \fBwebers\fP >"
.br
.ti -1c
.RI "using \fBmilliwebers\fP = \fBmilli\fP< \fBwebers\fP >"
.br
.ti -1c
.RI "using \fBkilowebers\fP = \fBkilo\fP< \fBwebers\fP >"
.br
.ti -1c
.RI "using \fBmegawebers\fP = \fBmega\fP< \fBwebers\fP >"
.br
.ti -1c
.RI "using \fBgigawebers\fP = \fBgiga\fP< \fBwebers\fP >"
.br
.ti -1c
.RI "using \fBmaxwells\fP = \fBunit\fP< std::ratio< 1, 100000000 >, \fBwebers\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBweber\fP = \fBwebers\fP"
.br
.ti -1c
.RI "using \fBpicoweber\fP = picowebers"
.br
.ti -1c
.RI "using \fBnanoweber\fP = nanowebers"
.br
.ti -1c
.RI "using \fBmicroweber\fP = microwebers"
.br
.ti -1c
.RI "using \fBmilliweber\fP = milliwebers"
.br
.ti -1c
.RI "using \fBkiloweber\fP = kilowebers"
.br
.ti -1c
.RI "using \fBmegaweber\fP = megawebers"
.br
.ti -1c
.RI "using \fBgigaweber\fP = gigawebers"
.br
.ti -1c
.RI "using \fBmaxwell\fP = \fBmaxwells\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBweber_t\fP = \fBunit_t\fP< \fBweber\fP >"
.br
.ti -1c
.RI "using \fBpicoweber_t\fP = \fBunit_t\fP< picoweber >"
.br
.ti -1c
.RI "using \fBnanoweber_t\fP = \fBunit_t\fP< nanoweber >"
.br
.ti -1c
.RI "using \fBmicroweber_t\fP = \fBunit_t\fP< microweber >"
.br
.ti -1c
.RI "using \fBmilliweber_t\fP = \fBunit_t\fP< milliweber >"
.br
.ti -1c
.RI "using \fBkiloweber_t\fP = \fBunit_t\fP< kiloweber >"
.br
.ti -1c
.RI "using \fBmegaweber_t\fP = \fBunit_t\fP< megaweber >"
.br
.ti -1c
.RI "using \fBgigaweber_t\fP = \fBunit_t\fP< gigaweber >"
.br
.ti -1c
.RI "using \fBmaxwell_t\fP = \fBunit_t\fP< \fBmaxwell\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBWb\fP = \fBwebers\fP"
.br
.ti -1c
.RI "using \fBpWb\fP = picowebers"
.br
.ti -1c
.RI "using \fBnWb\fP = nanowebers"
.br
.ti -1c
.RI "using \fBuWb\fP = microwebers"
.br
.ti -1c
.RI "using \fBmWb\fP = milliwebers"
.br
.ti -1c
.RI "using \fBkWb\fP = kilowebers"
.br
.ti -1c
.RI "using \fBMWb\fP = megawebers"
.br
.ti -1c
.RI "using \fBGWb\fP = gigawebers"
.br
.ti -1c
.RI "using \fBMx\fP = \fBmaxwells\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing \fBmagnetic_flux\fP values 

The SI unit for \fBmagnetic_flux\fP is \fCwebers\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCmagnetic_flux_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
