.TH "UnitContainers" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitContainers \- Unit Containers
.PP
Defines a series of classes which contain dimensioned values\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBunits::unit_t< Units, T, NonLinearScale >\fP"
.br
.RI "\fIContainer for values which represent quantities of a given unit\&. \fP"
.ti -1c
.RI "struct \fBunits::unit_value_t< Units, Num, Denom >\fP"
.br
.RI "\fIStores a rational unit value as a compile-time constant\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines a series of classes which contain dimensioned values\&. 

Unit containers store a value, and support various arithmetic operations\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
