.TH "units::pressure" 3 "Sun Apr 3 2016" "Version 2.0.0" "Unit Conversion and Dimensional Analysis Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units::pressure \- namespace for unit types and containers representing pressure values  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.PP
.RI "\fBUnits (full names plural)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBpascals\fP = \fBunit\fP< std::ratio< 1 >, \fBcategory::pressure_unit\fP >"
.br
.ti -1c
.RI "using \fBbars\fP = \fBunit\fP< std::ratio< 100 >, \fBkilo\fP< \fBpascals\fP >>"
.br
.ti -1c
.RI "using \fBatmospheres\fP = \fBunit\fP< std::ratio< 101325 >, \fBpascals\fP >"
.br
.ti -1c
.RI "using \fBpounds_per_square_inch\fP = \fBcompound_unit\fP< force::pounds, \fBinverse\fP< \fBsquared\fP< \fBlength::inch\fP >>>"
.br
.ti -1c
.RI "using \fBtorrs\fP = \fBunit\fP< std::ratio< 1, 760 >, \fBatmospheres\fP >"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (full names singular)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBpascal\fP = \fBpascals\fP"
.br
.ti -1c
.RI "using \fBbar\fP = \fBbars\fP"
.br
.ti -1c
.RI "using \fBatmosphere\fP = \fBatmospheres\fP"
.br
.ti -1c
.RI "using \fBpound_per_square_inch\fP = pounds_per_square_inch"
.br
.ti -1c
.RI "using \fBtorr\fP = \fBtorrs\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnits (abbreviated names)\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "using \fBPa\fP = \fBpascals\fP"
.br
.ti -1c
.RI "using \fBatm\fP = \fBatmospheres\fP"
.br
.ti -1c
.RI "using \fBpsi\fP = pound_per_square_inch"
.br
.in -1c
.in -1c
.PP
.RI "\fBUnit Containers\fP"
.br

.PP
.in +1c
.in +1c
.ti -1c
.RI "using \fBpascal_t\fP = \fBunit_t\fP< \fBpascal\fP >"
.br
.ti -1c
.RI "using \fBbar_t\fP = \fBunit_t\fP< \fBbar\fP >"
.br
.ti -1c
.RI "using \fBatmosphere_t\fP = \fBunit_t\fP< \fBatmosphere\fP >"
.br
.ti -1c
.RI "using \fBpound_per_square_inch_t\fP = \fBunit_t\fP< pound_per_square_inch >"
.br
.ti -1c
.RI "using \fBtorr_t\fP = \fBunit_t\fP< \fBtorr\fP >"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
namespace for unit types and containers representing pressure values 

The SI unit for pressure is \fCpascals\fP, and the corresponding \fC\fBbase_unit\fP\fP category is \fCpressure_unit\fP\&. 
.PP
\fBSee also:\fP
.RS 4
See \fBunit_t\fP for more information on \fBunit\fP type containers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Unit Conversion and Dimensional Analysis Library from the source code\&.
